--INSERT INTO FitnesCentar (nazivFC, adresaFC, telefonFC, emailFC) VALUES ('FTN Gym','Neka Lepa Ulica 22','063444771','ftngym@gmail.com');
--INSERT INTO FitnesCentar (nazivFC, adresaFC, telefonFC, emailFC) VALUES ('PMF Gains','Matematička 32','0634543671','mat.Gym@gmail.com');
